### ISSUE TITLE
Brushes inclusion on Jehan/mypaint-brushes?

### ISSUE THREAD

**Issue by Jehan** [mypaint/mypaint-brushes#1]
On the original repo, I had 3 feature requests about adding some additional sets of brushes: 
https://github.com/Jehan/mypaint-brushes/issues/1
https://github.com/Jehan/mypaint-brushes/issues/2
https://github.com/Jehan/mypaint-brushes/issues/3

I didn't want to act on them because I didn't want to make decision about the future contents of "what is a good default brush set for MyPaint tools across various software?".
Should it be very very complete/exhaustive? Should it be just the bare minimum of more essential brushes? Something else?

Anyway now that the repository is upstream, I guess it is time to look into these brush addition proposals and make a decision maybe?
Could someone have a look at these? @briend maybe?

**Comment by briend** [comment]
Maybe the mypaint-brushes can be fairly exhaustive, and programs can (optionally) decide which particular brush groups are visible/default.  My main concern is the licensing as noted here: https://github.com/mypaint/mypaint/wiki/Licensing-policy
A lot of these brush packs were made with CC 3.0 (likely because 4.0 didn't exist!).  So, maybe the simplest thing would be to ask the brush authors to re-release the packs w/ an updated license?
https://creativecommons.org/share-your-work/licensing-considerations/version4/
Of course that has me wondering about the licenses for the brushes already added to the repo.  Deevad is clearly labeled CC0/public domain, but the others not so much.
I hate licensing :-)

**Comment by Jehan** [comment]
Hi!

> Of course that has me wondering about the licenses for the brushes already added to the repo. 

Current licensing is detailed in this file (which is basically the same `Licenses.dep5` from MyPaint repository, except that I cleaned it down to only show brushes, if I recall): https://github.com/mypaint/mypaint-brushes/blob/master/Licenses.dep5

Unless mistaken, it seems all the brushes are currently CC0. And that makes sense, you certainly don't want whatever brush you use to add any kind of co-authorship to your painting just because you used a brush. Neither do you want license propagation as well (as much as I like the share-alike condition for things I make, this would be going too far for just base data such as brushes).

So I think it would make sense to impose that any brush in the official `mypaint-brushes` package be public domain/CC0. By the way, what does this mean (from the wiki you linked):

> Alternatively, use CC BY (or CC BY-SA) 4.0 for the visible parts, but keep the raw brush settings public domain.

Does it mean like the preview image which can be CC by or by-sa?

> A lot of these brush packs were made with CC 3.0 (likely because 4.0 didn't exist!). 

Which exact CC license was it that you saw?

As for the 3 packages proposed originally, only the link from  Jehan/mypaint-brushes#1 is still available and I can't find a single licensing information in the archive (but maybe I'm blind!).

**Comment by Jehan** [comment]
Ok so I took the liberty to update the README with the wiki text (a bit extended but keeping the same base/meaning).

With this, I will close this report, and will write comments on all 3 original reports (from the previous repository location) to ask the reporter to make new reports here, and to ensure first that licensing is all right before doing so.

```
commit 5adf08db45aa18a2ceeac1d5084e8e5de57caea9 (HEAD -> master, origin/master, origin/HEAD)
Author: Jehan <jehan@girinstud.io>
Date:   Tue Jul 16 11:24:16 2019 +0200

    Issue #1: update the README with a licensing policy.
    
    This policy comes from the MyPaint wiki. Let's make it more visible into
    the brush repository itself.

 README.md | 20 ++++++++++++++++++++
 1 file changed, 20 insertions(+)
```
