### ISSUE TITLE
Release a stable mypaint-brushes v1?

### ISSUE THREAD

**Issue by Jehan** [mypaint/mypaint-brushes#4]
There is not much which happened on the v1 side, so it may look like not worthy, but there is this one commit about automake 1.16 support. Right now distributions have to patch the autogen.sh script themselves when they want to build with this newer version of automake.

Now maybe it's not too big of a problem, I don't know. But making a new release (1.4.0? 1.3.1?) should not take too much time either. :-)

Same as:
https://github.com/mypaint/libmypaint/issues/143

**Comment by briend** [comment]
good idea!  I'm thinking 1.3.1 should be fine although it does bug me a tiny bit to not match libmypaint :-P...  hmm.  Should I expect make distcheck to succeed and produce a tar?  Have you tried it before?  I'm getting this error:
`
Making all in brushes
make[2]: Entering directory '/home/bd/code/mypaint/mypaint-brushes/mypaint-brushes-1.3.1/_build/sub/brushes'
make[2]: *** No rule to make target 'order.conf', needed by 'all-am'.  Stop.
make[2]: Leaving directory '/home/bd/code/mypaint/mypaint-brushes/mypaint-brushes-1.3.1/_build/sub/brushes'
Makefile:380: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bd/code/mypaint/mypaint-brushes/mypaint-brushes-1.3.1/_build/sub'
Makefile:585: recipe for target 'distcheck' failed
make: *** [distcheck] Error 1
`

**Comment by Jehan** [comment]
It should. It means there is a bug un a makefile. I'll fix.

Le 4 septembre 2019 04:52:30 GMT+02:00, Brien Dieterle <notifications@github.com> a écrit :
>good idea!  I'm thinking 1.3.1 should be fine although it does bug me a
>tiny bit to not match libmypaint :-P...  hmm.  Should I expect make
>distcheck to succeed and produce a tar?  Have you tried it before?  I'm
>getting this error:
>
>Making all in brushes
>make[2]: Entering directory
>'/home/bd/code/mypaint/mypaint-brushes/mypaint-brushes-1.3.1/_build/sub/brushes'
>make[2]: *** No rule to make target 'order.conf', needed by 'all-am'. 
>Stop.
>make[2]: Leaving directory
>'/home/bd/code/mypaint/mypaint-brushes/mypaint-brushes-1.3.1/_build/sub/brushes'
>Makefile:380: recipe for target 'all-recursive' failed
>make[1]: *** [all-recursive] Error 1
>make[1]: Leaving directory
>'/home/bd/code/mypaint/mypaint-brushes/mypaint-brushes-1.3.1/_build/sub'
>Makefile:585: recipe for target 'distcheck' failed
>make: *** [distcheck] Error 1
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mypaint/mypaint-brushes/issues/4#issuecomment-527717360

-- 
ZeMarmot: https://film.zemarmot.net

**Comment by Jehan** [comment]
@briend It's fixed now. Apparently _DATA lists are not included into distribution by default (unlike _SOURCES for instance), which sucks. Anyway now fixed both in the 1.3.x branch and the master branch.

Anyway now distcheck should work for you too.

P.S.: wow Github is really stupid, it was not able to properly remove the whole quoted and signature parts when answering directly by email!

**Comment by Jehan** [comment]
@briend @jplloyd ?

**Comment by jplloyd** [comment]
I just cherry picked the size reduction stuff and assumed that everything else was in order.
https://github.com/mypaint/mypaint-brushes/releases/tag/v1.3.1

**Comment by Jehan** [comment]
Awesome, thanks!
